#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 8i0.
#+    Returns a page containing "Holberton School" when queried
#+     at the root with a curl GET request.
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".

sudo apt-get update -y;
sudo apt-get install -y nginx;
sudo apt-get install -y ufw;

sudo ufw enable;
sudo ufw allow 'Nginx HTTP';
sudo ufw allow 'OpenSSH';

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html;

sudo cp ./nginx.conf /etc/nginx/sites-enabled/default;

sudo service nginx restart;
